### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by tincho70** [MostroP2P/mostro-web#11]
When trying to access with a private key (in hexadecimal format) you see the following error in the console

```
entry.fzB2cQAo.js:4 Error: private key must be 32 bytes, hex or bigint, not string
    at Object.mr [as normPrivateKeyToScalar] (entry.fzB2cQAo.js:17:48900)
    at schnorrGetExtPubKey (entry.fzB2cQAo.js:17:64467)
    at Object.schnorrGetPublicKey [as getPublicKey] (entry.fzB2cQAo.js:17:64953)
    at getPublicKey (entry.fzB2cQAo.js:2065:29008)
    at new $o (entry.fzB2cQAo.js:2139:78742)
    at entry.fzB2cQAo.js:2145:94508
    at callWithErrorHandling (entry.fzB2cQAo.js:4:862)
    at callWithAsyncErrorHandling (entry.fzB2cQAo.js:4:996)
    at Sr (entry.fzB2cQAo.js:4:16114)
    at callWithErrorHandling (entry.fzB2cQAo.js:4:872)
```

**Comment by bilthon** [comment]
Fixed  [here](89f4b3c),  published in v0.0.17
